server:
  port: 80
  servlet:
    session:
      #      timeout: 20s
      cookie:
        http-only: true
  #        secure: true
spring:
  datasource:
    url: jdbc:mysql://fgc_mysql_prod:3306/forget_cmd?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=GMT&jdbcCompliantTruncation=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
