server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://fgc_mysql_prod:3306/forget_cmd?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=GMT&jdbcCompliantTruncation=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update